const selects = {
  step1: {
    photo: 'input[type="file"][name="photo"]',
    lastName: 'input[type="text"][name="apply.lastName"]', // Family Name (as on passport)
    noLastName: 'input[type="checkbox"][name="noLastName"]', //The family name field in the passport is empty
    name: 'input[type="text"][name="apply.name"]', //Chinese Name
    noName: 'input[type="checkbox"][name="noName"]', // Given Name (as on passport)
    //The given name field in the passport is empty
    noGivenName: 'input[type="checkbox"][name="noGivenName"]',
    //Gender
    genderMale: 'input[name="apply.sex"][value="0"]',
    genderFemale: 'input[name="apply.sex"][value="1"]',
    //Marital Status
    marryStatusuNMARRIED:
      'input[type="radio"][name="apply.marryStatus"][value="0"]',
    marryStatusMARRIED:
      'input[type="radio"][name="apply.marryStatus"][value="1"]',
    //Nationality
    countryId: 'select[name="apply.countryId"]',
    //birthDate: 'input[type="text"][name="apply.bornedDate"]',
    birthDate: 'input[name="apply.bornedDate"]',
    placeOfBirth: 'input[type="text"][name="apply.bornedAddress"]',
    bornedCountryId: 'select[name="apply.bornedCountryId"]',
    //Native Language
    languageId: 'select[name="apply.languageId"]',
    // Religion
    religionId: 'select[name="apply.religionId"]',
    otherReligion: 'input[type="text"][name="apply.otherReligion"]',
    //Highest Level of Education Completed/to be Completed
    educationId: 'select[name="apply.educationId"]',
    //Intitution of Highest Diploma
    lastSchool: 'input[type="text"][name="applyEx.lastSchool"]',
    //Current Employer or Educational Institution

    currentEmployer: 'input[name="apply.workplace"]',
    //Health Status
    healthStatus: 'input[name="apply.healthStatus"]',
    //  Occupation
    careerId: 'select[name="apply.careerId"]',
    careerName: 'input[type="text"][name="apply.careerName"]',
    //Hobby
    hobby: 'input[type="text"][name="apply.hobby"]',
    //Passport Number
    passportNo: 'input[type="text"][name="apply.passportNo"]',
    //Passport Expiry Date
    passportExpire: 'input[type="text"][name="apply.passportExpire"]',
    //Are you Ethnic Chinese?
    applisOverseaTrue:
      'input[type="radio"][name="apply.isOversea"][value="true"]', // false mane no true mane yes
    appliOverseaFalse:
      'input[type="radio"][name="apply.isOversea"][value="false"]',
    //Whether in Chinese mainland now?
    inChinaOnApplyYES: 'input[type="radio"][name="applyEx.inChinaOnApply"][value="true"]',
    inChinaOnApplyNO: 'input[type="radio"][name="applyEx.inChinaOnApply"][value="false"]',
    //Current School / Organisation
    chinaPlaceOnApply: 'input[type="text"][name="applyEx.chinaPlaceOnApply"]',
    //Visa Type
    visaId: 'select[name="apply.visaId"]',
    //Visa No.
    visaNo: 'input[type="text"][name="apply.visaNo"]',
    //Visa Expiry Date
    visaExpire: 'input[type="text"][name="apply.visaExpire"]',
    //Place of Issue
    issuePlace: 'select[name="applyEx.issuePlace"]',
    otherIssuePlace: 'input[type="text"][name="otherIssuePlace"]',
    //Purpose for Residence
    residencePurpose: 'select[name="applyEx.residencePurpose"]',
    // others purpose for residence
    residenceOther: 'input[type="text"][name="applyEx.residenceOther"]',
    //Emigrant from Chinese mainland, Hong Kong, Macau, and Taiwan?
     isYiMinYes: 'input[type="radio"][name="applyEx.isYiMin"][value="true"]', // false means no true means yes
    isYiMinNo: 'input[type="radio"][name="applyEx.isYiMin"][value="false"]',
    //Place of Origin in China
    restrict: 'select[name="apply.restrict"]',
  //Start date of the current citizenship
  gainCountryDate: 'input[type="text"][name="apply.gainCountryDate"]',
  

  },
  step2:{
    //Language Proficiency
      //Chinese Proficiency
            languageSkillId: 'select[name="apply.languageSkillId"]',
            //level of hsk
            hskId: 'select[name="apply.hskId"]',
            //scores
            hskScore: 'input[type="text"][name="apply.hskScore"]',
            //	*HSK Test Score Report No
              hskNo: 'input[type="text"][name="applyEx.hskNo"]',
              //Level of HSKK
              hskOralId: 'select[name="apply.hskOralId"]',
            //scores
            hskkScore: 'input[type="text"][name="apply.hskkScore"]',
       //english Proficiency
        //Language Proficiency	
         englishLanguageSkillId: 'select[name="apply.englishLanguageSkillId"]',
        //Certificate of English Proficiency
        yydjzs: 'select[name="apply.yydjzs"]', 
        //Other Certificate
        otherYydjzs: 'input[type="text"][name="apply.otherYydjzs"]',
        //English Score
        yydjzsScore: 'input[type="text"][name="apply.yydjzsScore"]',
        //*Certificate issue date
        yydjzsIssueDate: 'input[type="text"][name="apply.yydjzsIssueDate"]',
        //Other Language Proficiency
        otherLanguage: 'input[type="text"][name="apply.otherLanguage"]',
  //Recommender
     //Name
     guarantorEnname: 'input[type="text"][name="apply.guarantorEnname"]',
     //Relationship with the applicant
     guarRelation: 'input[type="text"][name="apply.guarRelation"]',
     //Organization
     guarWorkplace: 'input[type="text"][name="apply.guarWorkplace"]',     
     //mobile
     guarMobile: 'input[type="text"][name="apply.guarMobile"]',
     //Phone Number
     guarPhone: 'input[type="text"][name="apply.guarPhone"]',
     //*Email
     guarEmail: 'input[type="text"][name="apply.guarEmail"]',
     //Nationality
     guarCountryId: 'select[name="apply.guarCountryId"]',
    //Job Title
    guarCareer: 'input[type="text"][name="apply.guarCareer"]',
    //Address 
    guarAddress: 'input[type="text"][name="apply.guarAddress"]',
     //Fax Number
      guarFax: 'input[type="text"][name="apply.guarFax"]',
  },
  step3:{
       // here we ae handle must be 3 element
     //Year Attended (From)
     shStartDate: 'input[type="text"][name="sh.startDate"]',
      //Year Attended (To)
      shEndDate: 'input[type="text"][name="sh.endDate"]',
      //School Name(Full Name)
      shStudyPlace: 'input[type="text"][name="sh.studyPlace"]',
     // Education Level	
     shEducationId: 'select[name="sh.educationId"]',
     //Field of Study
     shStuhisMajor: 'input[type="text"][name="sh.stuhisMajor"]',
     //add btn 
    //  addStudyHistoryButton: 'input[type="button"].el-button.el-button--primary.is-plain.append[value="Add"]',
    addStudyHistoryButton: 'input[type="button"][value="Add"]',
 //Have you ever studied online or offline at any institution in China
 haveStudiedInChinaYes: 'input[type="radio"][name="applyEx.haveStudiedInChina"][value="1"]',
 haveStudiedInChinaNo: 'input[type="radio"][name="applyEx.haveStudiedInChina"][value="0"]',
 //Name of the Institution
 learningInstitutionType: 'select[name="applyEx.learningInstitutionType"]',
// as a 
zxxxAsBody: 'select[name="applyEx.zxxxAsBody"]',
learningInstitutionName: 'input[type="text"][name="applyEx.learningInstitutionName"]',
zxxxAsOther: 'input[type="text"][name="applyEx.zxxxAsOther"]',
//Dates Attended (from/to)
learningStartDate: 'input[type="text"][name="applyEx.learningStartDate"]',
learningEndDate: 'input[type="text"][name="applyEx.learningEndDate"]',
//Contact Information of Your Student Counselor
//name
zxxxFdyName: 'input[type="text"][name="applyEx.zxxxFdyName"]',
//Telephone
zxxxFdyTel: 'input[type="text"][name="applyEx.zxxxFdyTel"]',
//Email Address|
zxxxFdyEmail: 'input[type="text"][name="applyEx.zxxxFdyEmail"]',


//Employment Background

// Do you have work experience? - Yes
"haveWorkHistory_yes": 'input[type="radio"][name="haveWorkHistory"][value="1"]',

// Do you have work experience? - No
"haveWorkHistory_no": 'input[type="radio"][name="haveWorkHistory"][value="0"]',

// Work History - Start Date (Year Attended From)
"wh.startDate": 'input[type="text"][name="wh.startDate"]',

// Work History - End Date (Year Attended To)
"wh.endDate": 'input[type="text"][name="wh.endDate"]',

// Work History - Company
"wh.workPlace": 'input[type="text"][name="wh.workPlace"]',

// Work History - Job Title
"wh.career": 'input[type="text"][name="wh.career"]',


// Add button
"addWorkHistory": 'input[type="button"][value="Add"]',

// Have you ever worked in China? - Yes
"haveWorkedInChina_yes": 'input[type="radio"][name="applyEx.haveWorkedInChina"][value="1"]',

// Have you ever worked in China? - No
"haveWorkedInChina_no": 'input[type="radio"][name="applyEx.haveWorkedInChina"][value="0"]',

// Name of the Institution (worked in China)
"workingInstitutionName": 'input[type="text"][name="applyEx.workingInstitutionName"]',

// Employment Start Date (worked in China)
"workingStartDate": 'input[type="text"][name="applyEx.workingStartDate"]',

// Employment End Date (worked in China)
"workingEndDate": 'input[type="text"][name="applyEx.workingEndDate"]',

// save and next 
saveAndNextButton: 'input[type="button"][value="Save and Next"]',
// saveAndNextButton: 'input[type="button"].el-button.el-button--primary[value="Save and Next"]',

  }
};
const zxxxAsBody = {
  ZXXX_AS_VISITING_STUDENT: "1",
ZXXX_AS_WINTER_SUMMER_CAMP: "2",
ZXXX_AS_HIGHSCHOOL_STUDENT: "3",
ZXXX_AS_BACHELOR_STUDENT: "4",
ZXXX_AS_MASTER_STUDENT: "5",
ZXXX_AS_PHD_STUDENT: "6",
ZXXX_AS_OTHER: "9",
}
const learningInstitutionType={LEARNING_INSTITUTION_UESTC: "1",
LEARNING_INSTITUTION_OTHER: "0",}

const shEducationId = {
  SH_EDUCATION_ELEMENTARY: "9",
SH_EDUCATION_JUNIOR_HIGH: "6",
SH_EDUCATION_SENIOR_HIGH: "1",
SH_EDUCATION_TECHNICAL_SECONDARY: "7F726D3B46BA49B1A325B51A3020B84C",
SH_EDUCATION_PRE_UNIVERSITY: "10",
SH_EDUCATION_VISITING: "11",
SH_EDUCATION_VOCATIONAL_COLLEGE: "2",
SH_EDUCATION_BACHELOR: "3",
SH_EDUCATION_CURRENTLY_UNDERGRADUATE: "12",
SH_EDUCATION_MASTER: "4",
SH_EDUCATION_CURRENTLY_MASTERS: "14",
SH_EDUCATION_DOCTOR: "5",
SH_EDUCATION_CURRENTLY_PHD: "13",
}
const guarCountryId = {
  Albania: "7",
  Algeria: "8",
  Afghanistan: "9",
  Argentina: "10",
  UnitedArabEmirates: "11",
  Aruba: "12",
  Oman: "13",
  Azerbaijan: "14",
  Egypt: "15",
  Ethiopia: "16",
  Ireland: "17",
  Estonia: "18",
  Andorra: "19",
  Angola: "20",
  Anguilla: "21",
  AntiguaAndBarbuda: "22",
  Austria: "23",
  Australia: "24",
  Barbados: "25",
  PapuaNewGuinea: "26",
  Bahamas: "27",
  Pakistan: "28",
  Paraguay: "29",
  Palestine: "30",
  Bahrain: "31",
  Panama: "32",
  Brazil: "33",
  Belarus: "34",
  Bermuda: "35",
  Bulgaria: "36",
  NorthernMarianaIslands: "37",
  NorthMacedonia: "130",
  Benin: "38",
  Belgium: "39",
  Iceland: "40",
  PortoRico: "42",
  BosniaAndHerzegovina: "44",
  Poland: "43",
  Bolivia: "41",
  Belize: "46",
  Botswana: "45",
  Bhutan: "47",
  Burkinabe: "48",
  Burundi: "49",
  BouvetIsland: "50",
  DPRKorea: "51",
  EquatorialGuinea: "52",
  Denmark: "53",
  Germany: "54",
  TimorLeste: "55",
  Togo: "56",
  DominicanRepublic: "57",
  Dominica: "58",
  RussianFederation: "59",
  Ecuador: "60",
  Eritrea: "61",
  France: "62",
  FaroeIslands: "63",
  FrenchPolynesia: "64",
  FrenchGuiana: "65",
  FrenchSouthernTerritories: "66",
  Vatican: "241",
  Philippines: "67",
  Fiji: "242",
  Finland: "68",
  CapeVerde: "69",
  Gambia: "70",
  Congo: "71",
  CongoKinshasa: "72",
  Colombia: "73",
  CostaRica: "74",
  Grenada: "75",
  Greenland: "76",
  Georgia: "77",
  Cuba: "78",
  Guadeloupe: "79",
  Guam: "80",
  Guyana: "81",
  Kazakhstan: "82",
  Haiti: "83",
  RepublicOfKorea: "84",
  Netherlands: "85",
  NetherlandsAntilles: "86",
  HeardIsland: "87",
  Montenegro: "88",
  Honduras: "89",
  Kiribati: "90",
  Djibouti: "91",
  Kyrgyzstan: "92",
  Guinea: "93",
  GuineaBissau: "94",
  Canada: "95",
  Ghana: "96",
  Gabon: "97",
  Cambodia: "98",
  CzechRepublic: "99",
  Zimbabwe: "100",
  Cameroon: "101",
  Qatar: "102",
  CaymanIslands: "103",
  CocosKeelingIslands: "104",
  Comoros: "105",
  CoteDIvoire: "106",
  Kuwait: "107",
  Croatia: "108",
  Kenya: "109",
  CookIslands: "110",
  Latvia: "111",
  Lesotho: "112",
  Laos: "113",
  Lebanon: "114",
  Lithuania: "117",
  Liberia: "115",
  Libya: "116",
  Liechtenstein: "118",
  Reunion: "119",
  Luxembourg: "120",
  Rwanda: "121",
  Romania: "122",
  Madagascar: "123",
  Maldives: "125",
  IslasMalvinas: "126",
  Malta: "124",
  Malawi: "127",
  Malaysia: "128",
  Mali: "129",
  MarshallIslands: "131",
  Martinique: "132",
  Mauritius: "133",
  Mauritania: "134",
  UnitedStates: "135",
  AmericanSamoa: "137",
  USVirginIslands: "138",
  Mongolia: "139",
  Montserrat: "140",
  Bangladesh: "141",
  Peru: "142",
  Micronesia: "143",
  Myanmar: "144",
  Moldova: "145",
  Morocco: "146",
  Monaco: "147",
  Mozambique: "148",
  Mexico: "149",
  Namibia: "150",
  SouthAfrica: "151",
  SouthSudan: "ff8080813736ea6901373b160b380125",
  Nauru: "240",
  Nepal: "153",
  Nicaragua: "154",
  Niger: "155",
  Nigeria: "156",
  Niue: "157",
  Norway: "158",
  NorfolkIsland: "159",
  Palau: "160",
  PitcairnIslands: "161",
  Portugal: "162",
  Japan: "163",
  Sweden: "164",
  Switzerland: "165",
  ElSalvador: "166",
  Samoa: "167",
  Serbia: "168",
  SierraLeone: "169",
  Senegal: "170",
  Cyprus: "171",
  Seychelles: "172",
  SaudiArabia: "173",
  ChristmasIsland: "174",
  SaoTomeAndPrincipe: "175",
  StHelena: "176",
  SaintKittsAndNevis: "177",
  SaintLucia: "178",
  SanMarino: "179",
  StPierreAndMiquelon: "180",
  StVincentAndGrenadines: "181",
  SriLanka: "182",
  Slovakia: "183",
  Slovenia: "184",
  Svalbard: "185",
  Swaziland: "186",
  Sudan: "187",
  Suriname: "188",
  SolomonIslands: "190",
  Somalia: "189",
  Tajikistan: "191",
  Thailand: "192",
  Tanzania: "193",
  Tonga: "194",
  TurksAndCaicos: "196",
  TrinidadAndTobago: "301",
  Tunisia: "197",
  Tuvalu: "198",
  Turkey: "199",
  Turkmenistan: "200",
  Tokelau: "201",
  WallisAndFutuna: "202",
  Vanuatu: "203",
  Guatemala: "204",
  Venezuela: "205",
  Brunei: "206",
  Uganda: "207",
  Ukraine: "208",
  Uruguay: "209",
  Uzbekistan: "210",
  Spain: "211",
  WesternSahara: "212",
  Greece: "214",
  Singapore: "215",
  NewCaledonia: "216",
  NewZealand: "217",
  Hungary: "218",
  Syria: "219",
  Jamaica: "220",
  Armenia: "221",
  JanMayen: "222",
  Yemen: "223",
  Iraq: "224",
  Iran: "225",
  Israel: "226",
  Italy: "227",
  India: "228",
  Indonesia: "229",
  UnitedKingdom: "230",
  BritishVirginIslands: "231",
  BritishIndianOceanTerritory: "232",
  Jordan: "233",
  Vietnam: "234",
  Zambia: "235",
  Chad: "236",
  Gibraltar: "237",
  Chile: "238",
  CentralAfricanRepublic: "239",
  China: "244",
}
const yydjzs = {ENGLISH_CERT_NONE: "0",
ENGLISH_CERT_IELTS: "1",
ENGLISH_CERT_TOEFL: "2",
ENGLISH_CERT_GRE: "3",
ENGLISH_CERT_GMAT: "4",
ENGLISH_CERT_DUOLINGO: "5",
ENGLISH_CERT_TOEIC: "6",
ENGLISH_CERT_PTE: "7",
ENGLISH_CERT_NATIVE: "8",
ENGLISH_CERT_OTHER: "9",}
const englishLanguageSkillId={ENGLISH_NONE: "1",
ENGLISH_POOR: "5",
ENGLISH_FAIR: "6",
ENGLISH_GOOD: "3",
ENGLISH_EXCELLENT: "2",}
const hskOralId={HSK_ORAL_NONE: "0",
HSK_ORAL_PRIMARY: "bbc03ada2dac3978012dac45ab170001",
HSK_ORAL_JUNIOR: "bbc03ada2dac3978012dac45fe670002",
HSK_ORAL_SENIOR: "bbc03ada2dac3978012dac4663c80003",}
const hskId = {HSK_NONE: "ff808081452c32c201453ed8684e1f91",
HSK_LEVEL_1: "bbc03ada2dac3978012dac47a2c00004",
HSK_LEVEL_2: "bbc03ada2dac3978012dac47b58d0005",
HSK_LEVEL_3: "bbc03ada2dac3978012dac47c5e80006",
HSK_LEVEL_4: "bbc03ada2dac3978012dac47d5f60007",
HSK_LEVEL_5: "bbc03ada2dac3978012dac47e7990008",
HSK_LEVEL_6: "bbc03ada2dac3978012dac47f8b00009",
HSK_LEVEL_7: "4FB54317BB59410EB740A91AFEEFE1FC",
HSK_LEVEL_8: "8BF554B00F7846BD942FDAC6BF7E95C9",
HSK_LEVEL_9: "F014DB6BC64841E4BC6BE14B68507751",}
const languageSkillId = {
  LANGUAGE_NONE: "1",
LANGUAGE_POOR: "5",
LANGUAGE_FAIR: "6",
LANGUAGE_GOOD: "3",
LANGUAGE_EXCELLENT: "2",
}
const restrictPlace={ChineseMainland: "0",
TaiWanChina: "1",
MacauChina: "2",
HongKongChina: "3"}
const residencePurposeId = {family_reunion: "1",
study: "2",
work: "3",
personal_affair: "4",
others: "9"}
const issuePlaceName = {
  Anhui: "PROVINCE_1",
  Beijing: "PROVINCE_2",
  Chongqing: "PROVINCE_3",
  Fujian: "PROVINCE_4",
  Guangdong: "PROVINCE_5",
  Gansu: "PROVINCE_6",
  Guangxi: "PROVINCE_7",
  Guizhou: "PROVINCE_8",
  Hebei: "PROVINCE_9",
  Hubei: "PROVINCE_10",
  Heilongjiang: "PROVINCE_11",
  Hainan: "PROVINCE_12",
  Henan: "PROVINCE_13",
  Hunan: "PROVINCE_14",
  Jilin: "PROVINCE_15",
  Jiangsu: "PROVINCE_16",
  Jiangxi: "PROVINCE_17",
  Liaoning: "PROVINCE_18",
  Neimenggu: "PROVINCE_19",
  Ningxia: "PROVINCE_20",
  Qinghai: "PROVINCE_21",
  Sichuan: "PROVINCE_22",
  Shandong: "PROVINCE_23",
  Shanghai: "PROVINCE_24",
  Shanxi: "PROVINCE_25",
  Shaanxi: "PROVINCE_26",
  Tianjin: "PROVINCE_27",
  Xizang: "PROVINCE_28",
  Xinjiang: "PROVINCE_29",
  Yunnan: "PROVINCE_30",
  Zhejiang: "PROVINCE_31",
  Other: "Other",
};
const visaId = {
  X1VISA: "ff80808140bf5b310140c7cb1acc1178",
  X2VISA: "ff80808140bf5b310140c7cb3e8e117a",
  ResidencePermit: "4",
  StayCertificate: "ff80808140e72a310140e85d6d4d091f",
  Others: "5",
  PermanentResidentID: "2C8EAC33BAF74DCA9164E88E74A15278",
  ZVISA: "ff80808153b231650153bc744cac2893",
  FVISA: "2",
  MVISA: "ff80808144613da50144668f49750e3e",
  LVISA: "1",
  S1VISA: "ff80808140bf5b310140c7ca822e116a",
  S2VISA: "ff80808140bf5b310140c7cae9061177",
  NoVisa: "28",
  Q1VISA: "ff808081518f467601518f657fb90036",
  Q2VISA: "ff808081518f467601518f6655a30039",
  KVISA: "2CBB73B36796458C8A0CC6F67B206A69",
};
const careerId = {
  Employee: "ff80808131d70e210131dadb4ef6000a",
  Student: "3",
  Teacher: "2",
  Doctor: "ff8080812ef58be3012ef5d7efb80004",
  Labourer: "4",
  ArmyService: "ff808081368270a901368a978ec20380",
  Engineers: "6",
  Scholars: "7",
  Housewife: "9",
  Retired: "8",
  Manager: "ff8080812ef58be3012ef5d7aaf20003",
  Officer: "ff80808131d70e210131dadd484a000b",
  Farmer: "5",
  Reporter: "91",
  MonksAndPriests: "92",
  Religious: "93",
  Others: "1",
};
const educationId = {
  ElementarySchool: "9",
  JuniorHigh: "6",
  SeniorHigh: "1",
  TechnicalSecondary: "7F726D3B46BA49B1A325B51A3020B84C",
  VocationalCollege: "2",
  Bachelor: "3",
  Master: "4",
  Dr: "5",
};
const countryId = {
  Afghanistan: "9",
  Albania: "7",
  Algeria: "8",
  AmericanSamoa: "137",
  Andorra: "19",
  Angola: "20",
  Anguilla: "21",
  AntiguaAndBarbuda: "22",
  Argentina: "10",
  Armenia: "221",
  Aruba: "12",
  Australia: "24",
  Austria: "23",
  Azerbaijan: "14",
  Bahamas: "27",
  Bahrain: "31",
  Bangladesh: "141",
  Barbados: "25",
  Belarus: "34",
  Belgium: "39",
  Belize: "46",
  Benin: "38",
  Bermuda: "35",
  Bhutan: "47",
  Bolivia: "41",
  BosniaAndHerzegovina: "44",
  Botswana: "45",
  BouvetIsland: "50",
  Brazil: "33",
  BritishIndianOceanTerritory: "232",
  BritishVirginIslands: "231",
  Brunei: "206",
  Bulgaria: "36",
  Burkinabe: "48",
  Burundi: "49",
  Cambodia: "98",
  Cameroon: "101",
  Canada: "95",
  CapeVerde: "69",
  CentralAfricanRepublic: "239",
  Chad: "236",
  Chile: "238",
  ChristmasIsland: "174",
  CocosKeelingIslands: "104",
  Colombia: "73",
  Comoros: "105",
  Congo: "71",
  CongoKinshasa: "72",
  CookIslands: "110",
  CostaRica: "74",
  CotedIvoire: "106",
  Croatia: "108",
  Cuba: "78",
  Cyprus: "171",
  DPRKCorea: "51",
  Denmark: "53",
  Djibouti: "91",
  Dominica: "58",
  DominicanRepublic: "57",
  Ecuador: "60",
  Egypt: "15",
  ElSalvador: "166",
  EquatorialGuinea: "52",
  Eritrea: "61",
  Estonia: "18",
  Ethiopia: "16",
  FaroeIslands: "63",
  Fiji: "242",
  Finland: "68",
  France: "62",
  FrenchGuiana: "65",
  FrenchPolynesia: "64",
  FrenchSouthernTerritories: "66",
  Gabon: "97",
  Gambia: "70",
  Georgia: "77",
  Germany: "54",
  Ghana: "96",
  Gibraltar: "237",
  Greece: "214",
  Greenland: "76",
  Grenada: "75",
  Guadeloupe: "79",
  Guam: "80",
  Guatemala: "204",
  Guinea: "93",
  GuineaBissau: "94",
  Guyana: "81",
  Haiti: "83",
  HeardIslandMcdonaldIslands: "87",
  Honduras: "89",
  Hungary: "218",
  Iceland: "40",
  India: "228",
  Indonesia: "229",
  Iran: "225",
  Iraq: "224",
  Ireland: "17",
  IslandsOfStPierreMiquelon: "180",
  IslasMalvinas: "126",
  Israel: "226",
  Italy: "227",
  Jamaica: "220",
  JanMayen: "222",
  Japan: "163",
  Jordan: "233",
  Kazakhstan: "82",
  Kenya: "109",
  Kiribati: "90",
  Kuwait: "107",
  Kyrgyzstan: "92",
  Laos: "113",
  Latvia: "111",
  Lebanon: "114",
  Lesotho: "112",
  Liberia: "115",
  Libya: "116",
  Liechtenstein: "118",
  Lithuania: "117",
  Luxembourg: "120",
  Madagascar: "123",
  Malawi: "127",
  Malaysia: "128",
  Maldives: "125",
  Mali: "129",
  Malta: "124",
  MarshallIslands: "131",
  Martinique: "132",
  Mauritania: "134",
  Mauritius: "133",
  Mexico: "149",
  Micronesia: "143",
  Moldova: "145",
  Monaco: "147",
  Mongolia: "139",
  Montenegro: "88",
  Montserrat: "140",
  Morocco: "146",
  Mozambique: "148",
  Myanmar: "144",
  Namibia: "150",
  Nauru: "240",
  Nepal: "153",
  Netherlands: "85",
  NetherlandsAntilles: "86",
  NewCaledonia: "216",
  NewZealand: "217",
  Nicaragua: "154",
  Niger: "155",
  Nigeria: "156",
  Niue: "157",
  NorfolkIsland: "159",
  NorthMacedonia: "130",
  NorthernMarianaIslands: "37",
  Norway: "158",
  Oman: "13",
  Pakistan: "28",
  Palau: "160",
  Palestine: "30",
  Panama: "32",
  PapuaNewGuinea: "26",
  Paraguay: "29",
  Peru: "142",
  Philippines: "67",
  PitcairnIslands: "161",
  Poland: "43",
  PortoRico: "42",
  Portugal: "162",
  Qatar: "102",
  RepublicOfKorea: "84",
  Reunion: "119",
  Romania: "122",
  RussianFederation: "59",
  Rwanda: "121",
  SaintKittsAndNevis: "177",
  SaintLucia: "178",
  Samoa: "167",
  SanMarino: "179",
  SaoTomeAndPrincipe: "175",
  SaudiArabia: "173",
  Senegal: "170",
  Serbia: "168",
  Seychelles: "172",
  SierraLeone: "169",
  Singapore: "215",
  Slovakia: "183",
  Slovenia: "184",
  SolomonIslands: "190",
  Somalia: "189",
  SouthAfrica: "151",
  SouthGeorgiaSouthSandwichIslands: "152",
  SouthSudan: "ff8080813736ea6901373b160b380125",
  Spain: "211",
  SriLanka: "182",
  StHelena: "176",
  StVincentGrenadines: "181",
  Sudan: "187",
  Suriname: "188",
  SvalbardArchipelago: "185",
  Swaziland: "186",
  Sweden: "164",
  Switzerland: "165",
  Syria: "219",
  Tajikistan: "191",
  Tanzania: "193",
  Thailand: "192",
  TheCaymanIslands: "103",
  TheCzechRepublic: "99",
  TimorLeste: "55",
  Togo: "56",
  Tokelau: "201",
  Tonga: "194",
  TrinidadAndTobago: "301",
  Tunisia: "197",
  Turkey: "199",
  Turkmenistan: "200",
  TurksAndCaicosIslands: "196",
  Tuvalu: "198",
  Uganda: "207",
  Ukraine: "208",
  UnitedArabEmirates: "11",
  UnitedKingdom: "230",
  UnitedStatesVirginIslands: "138",
  UnitedStatesOfAmerica: "135",
  Uruguay: "209",
  Uzbekistan: "210",
  Vanuatu: "203",
  Vatican: "241",
  Venezuela: "205",
  Vietnam: "234",
  WallisAndFutuna: "202",
  WesternSahara: "212",
  Yemen: "223",
  Zambia: "235",
  Zimbabwe: "100",
};
const languageId = {
  Chinese: "3",
  English: "2",
  Croatian: "4",
  Bulgarian: "5",
  German: "6",
  latvian: "7",
  Czech: "8",
  French: "9",
  Slovak: "10",
  Italian: "11",
  Dutch: "12",
  Macedonian: "13",
  Maltese: "14",
  Latin: "15",
  Finnish: "16",
  Albanian: "17",
  Irish: "18",
  Catalan: "19",
  Belarussian: "20",
  Icelandic: "21",
  SerbiaCroatian: "22",
  Romanian: "23",
  Portuguese: "24",
  Swedish: "25",
  Slovenian: "26",
  Ukrainian: "27",
  Spanish: "28",
  Greek: "29",
  Creole: "30",
  Danish: "33",
  Greenlandic: "34",
  Uzbek: "35",
  Arabic: "36",
  Persian: "37",
  Kyrgyz: "38",
  Georgian: "40",
  Burmese: "41",
  Lao: "42",
  Azerbaijani: "43",
  Pashto: "44",
  Filipino: "47",
  Armenian: "48",
  Kazak: "49",
  Russian: "50",
  Khmer: "51",
  Bhutanese: "53",
  Malay: "54",
  Nepali: "55",
  Turkish: "56",
  Thai: "57",
  Hebrew: "58",
  Japanese: "59",
  Vietnamese: "60",
  Swahili: "61",
  Somali: "62",
  Amharic: "63",
  Tswana: "64",
  Burundi: "66",
  Ewe: "67",
  Tigrinya: "68",
  Korean: "39",
  Comoros: "69",
  Sesotho: "71",
  Rwanda: "72",
  Afrikaans: "74",
  Sango: "75",
  Urdu: "80",
  Hindi: "81",
  Fula: "20233E7AF4E641E992128C5FB698D58A",
  Mongolian: "82",
  Ganda: "233F2FC29389441D99191F1B07BBE3D4",
  Indonesian: "83",
  Bengali: "84",
  Tamil: "86",
  Norwegian: "85",
  Hun: "87",
  Tajiki: "88",
  Polish: "90",
  others: "0",
  Sinhala: "91",
  Turkmen: "DBBB83DC61DC414AB55B153BB87B79D3",
  Malagasy: "CF5476201DC542AC9AF221A241880F21",
};
const religionId = {
  Anglican: "ff8080813f09a886013f0d0fe8920d11",
  Atheism: "ff808081311878ac01311c1b00560014",
  Mormon: "ff808081311878ac01311c1e0ca20015",
  Christianity: "1",
  Judaism: "2",
  Catholicism: "3",
  EasternOrthodoxy: "4",
  Hinduism: "6",
  Islam: "7",
  Buddhism: "8",
  Taoism: "A70358890C2849BEB22852EB68AC8E20",
  None: "13",
  Lutheranism: "7ABFF77AD46F42E0923CCF7C1B930759",
  Other: "12",
};
