const step4={
    //Family ata loop hobe(max 5, min 2)
    //Relationship
    fmRelativeId: 'select[name="fm.relativeId"]',
    //Name
    fmName: 'input[type="text"][name="fm.name"]',
    //Nationality
    fmCountryId: 'select[name="fm.countryId"]',
    //Birth Date
    birthDate: 'input[type="text"][name="apply.birthDate"]',
    //Phone Number
    fmPhone: 'input[type="text"][name="fm.phone"]',
    //Email
    email: 'input[type="text"][name="fm.email"]',
    //Position
    duty: 'input[type="text"][name="fm.duty"]',
    //Work Place
    workPlace: 'input[type="text"][name="fm.workPlace"]',
    // Set as emergency contact
    // checkboxHidden: 'input[type="checkbox"][onclick*="checkboxOnClickHidden"]',
    // checkboxHidden: 'input[type="checkbox"][onclick="checkboxOnClickHidden(this)"]',
    isEmergencyContactYes: 'input[type="hidden"][name="fm.isEmergencyContact"][value="1"]',
    isEmergencyContactNo: 'input[type="hidden"][name="fm.isEmergencyContact"][value="0"]',
    // delete btn
    deleteButton: 'input[type="button"][onclick*="deleteApplyFamilyMember3"]',
    //addbtn
    addButton: 'input[type="button"][onclick*="appendApplyFamilyMember3"]',
    fm_id: 'input[type="hidden"][name="fm.id"]',

    // ///////////////////////// Criminal Record////////////////////////
    //Have you ever had a criminal record?
    hasCriminalRecordYes: 'input[type="radio"][name="applyEx.hasCriminalRecord"][value="1"]',
   hasCriminalRecordNo: 'input[type="radio"][name="applyEx.hasCriminalRecord"][value="0"]',
   //Illegal Record Content
   criminalRecordContent: 'textarea[name="applyEx.criminalRecordContent"]',
   //////////////////////////Financial Supporter//////////////////////
   //Name
   selfSupporter: 'input[type="text"][name="apply.selfSupporter"]',
   //Addr
   selfaddress: 'input[type="text"][name="apply.selfaddress"]',
   //Tel
   selfphone: 'input[type="text"][name="apply.selfphone"]',
   //Relationship with applican
   ssrelative: 'input[type="text"][name="apply.ssrelative"]',
   //Organization
   selfwork: 'input[type="text"][name="apply.selfwork"]',
   //Email
   selfemail: 'input[type="text"][name="apply.selfemail"]',
                         /* Guarantor in China   */
  //Name
  emergencyName: 'input[type="text"][name="apply.emergencyName"]',
  //Mobile
  emergencyMobile: 'input[type="text"][name="apply.emergencyMobile"]',
  //*Phone Number
  emergencyPhone: 'input[type="text"][name="apply.emergencyPhone"]',
  //Email
  emergencyEmail: 'input[type="text"][name="apply.emergencyEmail"]',
  //Organization
  emergencyAddress: 'input[type="text"][name="apply.emergencyAddress"]',
  //Address
  emergencyZip: 'input[type="text"][name="apply.emergencyZip"]',
  //save
  saveButton: 'input[type="button"][onclick*="saveFamilyMember"]',
  //save and next \
  saveAndNextButton: 'input[type="button"][onclick*="saveFamilyMember"][value="Save and Next"]',

}
const fmCountryId={
  Albania: "7",
  Algeria: "8",
  Afghanistan: "9",
  Argentina: "10",
  UnitedArabEmirates: "11",
  Aruba: "12",
  Oman: "13",
  Azerbaijan: "14",
  Egypt: "15",
  Ethiopia: "16",
  Ireland: "17",
  Estonia: "18",
  Andorra: "19",
  Angola: "20",
  Anguilla: "21",
  AntiguaAndBarbuda: "22",
  Austria: "23",
  Australia: "24",
  Barbados: "25",
  PapuaNewGuinea: "26",
  Bahamas: "27",
  Pakistan: "28",
  Paraguay: "29",
  Palestine: "30",
  Bahrain: "31",
  Panama: "32",
  Brazil: "33",
  Belarus: "34",
  Bermuda: "35",
  Bulgaria: "36",
  NorthernMarianaIslands: "37",
  NorthMacedonia: "130",
  Benin: "38",
  Belgium: "39",
  Iceland: "40",
  PortoRico: "42",
  BosniaAndHerzegovina: "44",
  Poland: "43",
  Bolivia: "41",
  Belize: "46",
  Botswana: "45",
  Bhutan: "47",
  Burkinabe: "48",
  Burundi: "49",
  BouvetIsland: "50",
  DPRKorea: "51",
  EquatorialGuinea: "52",
  Denmark: "53",
  Germany: "54",
  TimorLeste: "55",
  Togo: "56",
  DominicanRepublic: "57",
  Dominica: "58",
  RussianFederation: "59",
  Ecuador: "60",
  Eritrea: "61",
  France: "62",
  FaroeIslands: "63",
  FrenchPolynesia: "64",
  FrenchGuiana: "65",
  FrenchSouthernTerritories: "66",
  Vatican: "241",
  Philippines: "67",
  Fiji: "242",
  Finland: "68",
  CapeVerde: "69",
  Gambia: "70",
  Congo: "71",
  CongoKinshasa: "72",
  Colombia: "73",
  CostaRica: "74",
  Grenada: "75",
  Greenland: "76",
  Georgia: "77",
  Cuba: "78",
  Guadeloupe: "79",
  Guam: "80",
  Guyana: "81",
  Kazakhstan: "82",
  Haiti: "83",
  RepublicOfKorea: "84",
  Netherlands: "85",
  NetherlandsAntilles: "86",
  HeardIsland: "87",
  Montenegro: "88",
  Honduras: "89",
  Kiribati: "90",
  Djibouti: "91",
  Kyrgyzstan: "92",
  Guinea: "93",
  GuineaBissau: "94",
  Canada: "95",
  Ghana: "96",
  Gabon: "97",
  Cambodia: "98",
  CzechRepublic: "99",
  Zimbabwe: "100",
  Cameroon: "101",
  Qatar: "102",
  CaymanIslands: "103",
  CocosKeelingIslands: "104",
  Comoros: "105",
  CoteDIvoire: "106",
  Kuwait: "107",
  Croatia: "108",
  Kenya: "109",
  CookIslands: "110",
  Latvia: "111",
  Lesotho: "112",
  Laos: "113",
  Lebanon: "114",
  Lithuania: "117",
  Liberia: "115",
  Libya: "116",
  Liechtenstein: "118",
  Reunion: "119",
  Luxembourg: "120",
  Rwanda: "121",
  Romania: "122",
  Madagascar: "123",
  Maldives: "125",
  IslasMalvinas: "126",
  Malta: "124",
  Malawi: "127",
  Malaysia: "128",
  Mali: "129",
  MarshallIslands: "131",
  Martinique: "132",
  Mauritius: "133",
  Mauritania: "134",
  UnitedStates: "135",
  AmericanSamoa: "137",
  USVirginIslands: "138",
  Mongolia: "139",
  Montserrat: "140",
  Bangladesh: "141",
  Peru: "142",
  Micronesia: "143",
  Myanmar: "144",
  Moldova: "145",
  Morocco: "146",
  Monaco: "147",
  Mozambique: "148",
  Mexico: "149",
  Namibia: "150",
  SouthAfrica: "151",
  SouthSudan: "ff8080813736ea6901373b160b380125",
  Nauru: "240",
  Nepal: "153",
  Nicaragua: "154",
  Niger: "155",
  Nigeria: "156",
  Niue: "157",
  Norway: "158",
  NorfolkIsland: "159",
  Palau: "160",
  PitcairnIslands: "161",
  Portugal: "162",
  Japan: "163",
  Sweden: "164",
  Switzerland: "165",
  ElSalvador: "166",
  Samoa: "167",
  Serbia: "168",
  SierraLeone: "169",
  Senegal: "170",
  Cyprus: "171",
  Seychelles: "172",
  SaudiArabia: "173",
  ChristmasIsland: "174",
  SaoTomeAndPrincipe: "175",
  StHelena: "176",
  SaintKittsAndNevis: "177",
  SaintLucia: "178",
  SanMarino: "179",
  StPierreAndMiquelon: "180",
  StVincentAndGrenadines: "181",
  SriLanka: "182",
  Slovakia: "183",
  Slovenia: "184",
  Svalbard: "185",
  Swaziland: "186",
  Sudan: "187",
  Suriname: "188",
  SolomonIslands: "190",
  Somalia: "189",
  Tajikistan: "191",
  Thailand: "192",
  Tanzania: "193",
  Tonga: "194",
  TurksAndCaicos: "196",
  TrinidadAndTobago: "301",
  Tunisia: "197",
  Tuvalu: "198",
  Turkey: "199",
  Turkmenistan: "200",
  Tokelau: "201",
  WallisAndFutuna: "202",
  Vanuatu: "203",
  Guatemala: "204",
  Venezuela: "205",
  Brunei: "206",
  Uganda: "207",
  Ukraine: "208",
  Uruguay: "209",
  Uzbekistan: "210",
  Spain: "211",
  WesternSahara: "212",
  Greece: "214",
  Singapore: "215",
  NewCaledonia: "216",
  NewZealand: "217",
  Hungary: "218",
  Syria: "219",
  Jamaica: "220",
  Armenia: "221",
  JanMayen: "222",
  Yemen: "223",
  Iraq: "224",
  Iran: "225",
  Israel: "226",
  Italy: "227",
  India: "228",
  Indonesia: "229",
  UnitedKingdom: "230",
  BritishVirginIslands: "231",
  BritishIndianOceanTerritory: "232",
  Jordan: "233",
  Vietnam: "234",
  Zambia: "235",
  Chad: "236",
  Gibraltar: "237",
  Chile: "238",
  CentralAfricanRepublic: "239",
  China: "244",
}
const fmRelativeId={FM_RELATIVE_FATHER: "bbc03ada2d7df96a012d7dfca4040001",
FM_RELATIVE_MOTHER: "bbc03ada2d7df96a012d7dfcdff40002",
FM_RELATIVE_SPOUSE: "ff8080812e89a880012e89fdbbe20001",
FM_RELATIVE_UNCLE: "bbc03ada2d7df96a012d7dfd8dd70005",
FM_RELATIVE_BROTHER: "bbc03ada2d7df96a012d7dfd152d0003",
FM_RELATIVE_SISTER: "bbc03ada2d7df96a012d7dfd55fe0004",
FM_RELATIVE_OTHERS: "ff8080812e71fae5012e7495a9140004",
FM_RELATIVE_CHILDREN: "8",}